linter:
  rules:
    - always_declare_return_types
    - always_specify_types
    - annotate_overrides
    - avoid_print
    - prefer_final_fields
    - unnecessary_new
    - prefer_const_constructors
    - prefer_single_quotes
    - lines_longer_than_80_chars
    - public_member_api_docs
    - sort_unnamed_constructors_first
    - type_annotate_public_apis
    - avoid_renaming_method_parameters
    - prefer_is_empty
    - prefer_is_not_empty
    - unnecessary_this
    - use_key_in_widget_constructors