name: strido
description: "Keep moving with Strido - A modern step tracking application."
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  pedometer: ^4.0.0
  permission_handler: ^11.3.1
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.4
  flutter_reactive_ble: ^5.0.2
  shared_preferences: ^2.2.3
  device_info_plus: ^10.0.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  screenshot: ^3.0.0
  share_plus: ^10.0.0
  flutter_local_notifications: ^19.5.0
  flutter_foreground_task: ^9.1.0
  workmanager: ^0.6.0
  provider: ^6.1.5+1
  image: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.5.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"  

flutter:
  uses-material-design: true

  assets:
    - assets/images/strido_story_bg.png
    - assets/fonts/
